name: Deploy Yarn CI

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: yarn install
      - name: Type check
        run: yarn tsc
      - name: Lint
        run: yarn eslint
      - name: Build
        run: yarn Build
        env:
          NODE_ENV: 'production'
      - name: Export
        run: |
          yarn Export
          touch out/.nojekyll
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
